// This file is auto-generated by `bun run gen:oxfmt-compatgen`, do not edit it manually.
import type { OxfmtConfig } from 'oxfmt';

export const config: OxfmtConfig = {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  arrowParens: 'always',
  trailingComma: 'es5',
  bracketSpacing: true,
  bracketSameLine: false,
  proseWrap: 'preserve',
  endOfLine: 'lf',
  quoteProps: 'as-needed',
  singleAttributePerLine: false,
  checkIgnorePragma: true,
  jsxSingleQuote: false,
  htmlWhitespaceSensitivity: 'css',
  embeddedLanguageFormatting: 'auto',
  sortPackageJson: false,
  ignorePatterns: [],
  sortImports: {
    groups: [
      'builtin',
      'external',
      'internal',
      ['parent', 'sibling', 'index'],
      'side_effect',
      'unknown',
    ],
    partitionByComment: true,
    newlinesBetween: false,
    order: 'asc',
  },
  overrides: [
    { files: ['**/*.json', '**/*.jsonc'], options: { trailingComma: 'none' } },
  ],
};

export default config;
