import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { styleText } from 'node:util';
import { createBaseProgram, runTask } from './utils';
import confirm from '@inquirer/confirm';

/**
 * Gets the local and remote swagger files and returns their content.
 *
 * @param options - The local swagger file path and the remote swagger URL.
 * @returns Resolves to the local and remote swagger file content, or rejects if an error occurs.
 */
async function getSwaggerFiles({
  localSwaggerPath,
  remoteSwaggerUrl,
}: {
  localSwaggerPath: string;
  remoteSwaggerUrl: string;
}) {
  const [localSwagger, remoteSwagger] = await Promise.all([
    runTask({
      name: 'Reading local swagger file',
      command: readFile(localSwaggerPath, 'utf8'),
    }),
    runTask({
      name: 'Reading server swagger file',
      command: `curl -s ${remoteSwaggerUrl}`,
    }),
  ]);
  return { localSwagger, remoteSwagger };
}

/**
 * Asks the user if they want to use the remote swagger and generate new API models.
 *
 * @param params - The local swagger file path, the remote swagger content, and the force generation flag.
 * @returns Resolves to true if the user confirms, otherwise false.
 */
async function syncSwaggerFiles({
  remoteSwagger,
  localSwaggerPath,
  forceGenModels,
}: {
  remoteSwagger: string;
  localSwaggerPath: string;
  forceGenModels: boolean;
}) {
  const userConfirmed = await confirm({
    message: !forceGenModels
      ? 'Do you want to use the remote swagger and generate new API models? (y/n)?'
      : 'Do you want to use the remote swagger? (y/n)?',
  });
  if (userConfirmed) {
    await runTask({
      name: 'Replacing local swagger.json with remote',
      command: writeFile(localSwaggerPath, remoteSwagger),
    });
    return true;
  }
  return false;
}

/**
 * Generates models and a swagger type definition file based on the provided input and output paths.
 * Optionally formats the generated files using a specified script.
 *
 * @param params - The input and output paths and the optional format script.
 * @returns Resolves when all tasks are completed or rejects if an error occurs.
 */
async function generateModels({
  localSwaggerPath,
  modelsFolder,
  formatScript,
}: {
  localSwaggerPath: string;
  modelsFolder: string;
  formatScript?: string;
}) {
  await runTask({
    name: 'Generating models',
    command: `npx openapi-typescript-codegen --input ${localSwaggerPath} --output ${modelsFolder} --client fetch`,
  });
  await runTask({
    name: 'Generating swagger type definition',
    command: async () => {
      const content = await readFile(localSwaggerPath, 'utf8');
      await writeFile(
        `${modelsFolder}/swagger.d.ts`,
        `/* generated -- do not edit */\n/* eslint-disable -- Autogenerated file */\ndeclare const schema: ${content}; export default schema;`
      );
    },
  });
  if (formatScript) {
    await runTask({
      name: 'Formatting models',
      command: `node --run ${formatScript}`,
    });
  }
}

/**
 * Main function to run the CLI script
 *
 * @param options - The CLI options.
 */
async function run({
  url: remoteSwaggerUrl,
  output: localSwaggerPath,
  modelsFolder,
  formatScript,
  forceGenModels,
}: {
  url: string;
  output: string;
  modelsFolder: string;
  formatScript?: string;
  forceGenModels?: boolean;
}) {
  console.log(styleText('magenta', '\n🚀 Swagger-sync ✨\n'));
  const hasLocalSwaggerPath = existsSync(localSwaggerPath);
  if (!hasLocalSwaggerPath) {
    await runTask({
      name: 'Downloading swagger.json',
      command: `curl ${remoteSwaggerUrl} -o ${localSwaggerPath}`,
    });
  }
  const { localSwagger, remoteSwagger } = await getSwaggerFiles({
    localSwaggerPath,
    remoteSwaggerUrl,
  });
  if (
    !hasLocalSwaggerPath ||
    JSON.stringify(JSON.parse(localSwagger)) !==
      JSON.stringify(JSON.parse(remoteSwagger))
  ) {
    console.log(
      styleText(
        'yellow',
        '\n⚠️  Local and remote swagger.json does not match!\n'
      )
    );
    const confirmed = await syncSwaggerFiles({
      localSwaggerPath,
      remoteSwagger,
      forceGenModels: !!forceGenModels,
    });
    if (!confirmed) {
      console.log(styleText('yellow', '\n⚠️  Sync remote swagger skipped.\n'));
      if (!forceGenModels) process.exit(0);
    }
  } else {
    if (!forceGenModels && existsSync(modelsFolder)) {
      console.log(
        styleText(
          'blue',
          '\nLocal and remote swagger are identical. No updates required.\n'
        )
      );
      process.exit(0);
    }
  }
  await generateModels({ localSwaggerPath, modelsFolder, formatScript });
  console.log(
    styleText('green', '\n✅ Sync swagger and models generation completed!\n')
  );
}

// Define and run the CLI program
createBaseProgram()
  .name('swagger-sync')
  .description(
    'A CLI tool to synchronize a local swagger file with a remote and generate API models.'
  )
  .requiredOption(
    '--url <url>',
    'The remote swagger file URL to download and compare.'
  )
  .requiredOption('--output <path>', 'The path to save the local swagger file.')
  .requiredOption(
    '--models-folder <path>',
    'The path to save the generated models and swagger type definition.'
  )
  .option(
    '--format-script <script>',
    'A package.json script to format the generated files.'
  )
  .option(
    '--force-gen-models',
    'Force the generation of models even if the local and remote swagger files are identical.'
  )
  .action(async (options) => {
    try {
      await run({
        url: options.url,
        output: options.output,
        modelsFolder: options.modelsFolder,
        formatScript: options.formatScript,
        forceGenModels: options.forceGenModels,
      });
    } catch (error) {
      console.error(error);
      process.exit(1);
    }
  })
  .parseAsync(process.argv);
