import { execFileSync } from 'node:child_process';
import { readFile, writeFile } from 'node:fs/promises';
import { runTask } from '../../utils';

/**
 * Generate an OpenAPI schema type definition file from an OpenAPI schema.
 *
 * @param input - The input OpenAPI schema path.
 * @param output - The output directory for generated models.
 */
export async function run(input: string, output: string) {
  await runTask({
    name: 'Generating schema types',
    command: async () => {
      execFileSync('npx', ['openapi-typescript', input, '-o', output], {
        shell: true,
      });
      const content = await readFile(output, 'utf8');
      await writeFile(
        output,
        `/* eslint-disable -- Autogenerated file */\n${content}`
      );
    },
  });
}
